### ISSUE TITLE
Support for Node 10.x

### ISSUE THREAD

**Issue by jckanthem** [puresec/FunctionShield#10]
Getting this build error on node 10.x: 
```
No native build was found for platform=darwin arch=x64 runtime=node abi=64 uv=1 libc=glibc
```
Are there plans to support 10.x in the near future with the aws lambda node8 runtime EOL approaching?

**Comment by 0xh0b0** [comment]
You should update your FunctionShield package to the latest version (>2.0.0) for Node 10 support.
Please note that FunctionShield is no longer being maintained and we do not recommend using it for production scenarios.
