### ISSUE TITLE
How do I know FunctionShield does what it says?

### ISSUE THREAD

**Issue by arminio** [puresec/FunctionShield#2]
Hi,
This looks very promising for our needs. However it's a lot to ask users to trust a closed source library like this. Can you please look into making the source code for libfunctionshieldcore.so available?

**Comment by oorryy** [comment]
Hi Arminio,

We understand your concern, and indeed we do not expect everyone to find it suitable and trust it blindly. However, it is a free library, and this is how it is currently offered. 

Having said that, our commercial product does provide all proper guarantees and relevant documentation.

**Comment by arminio** [comment]
Fair enough :)

**Comment by oorryy** [comment]
Issue is currently closed.
