### ISSUE TITLE
Guidance with an Express app running on AWS Lambda

### ISSUE THREAD

**Issue by gregmsanderson** [puresec/FunctionShield#5]
Hello,

I just tried the function shield with a simple function. And it worked. To test I'd added it correctly, I tried writing to /tmp. Sure enough, when I do that _right after_ adding this block ...

`const FunctionShield = require('@puresec/function-shield');
FunctionShield.configure({
    policy: {
        // 'block' mode => active blocking
        // 'alert' mode => log only
        // 'allow' mode => allowed, implicitly occurs if key does not exist
        outbound_connectivity: "alert",
        read_write_tmp: "block",
        create_child_process: "block",
        read_handler: "alert"
    },
    token: 'tokenhere'
});`

... it works. The write to /tmp is blocked. Nice.

But then I want to protect all routes and files as Express uses multiple ones. Not just one file with a function in. So I tried a write to /tmp in the app's _routes_ file (it uses serverless-http to run it). And that write to /tmp _wasn't_ blocked. So ... does that mean that block of code above needs including in every file? I'd assumed it kind of "wrapped" the function by putting it in the index file that serverless-http uses. But sounds like that's not the case. I just wondered if you had experience with running Express on Lambda and any thoughts about the best approach?

(I'm not particularly concerned about /tmp, that was just a test of the process. Since if it stops that, it must be working.)

Thanks!

**Comment by 0xh0b0** [comment]
Can you please write a minimal example of express app with FunctionShield that doesn't work as expected?

**Comment by gregmsanderson** [comment]
Well it may be that I didn't understand it rather than it wasn't working correctly. Since I've got it working. I think.

What I initially did was only add it to the file that would have the normal Lambda event handler function (here it looks a little different because the serverless-http wraps it, to make it work for the Express req/res):

```
const serverless = require('serverless-http');
const app = require('./app');
const handler = serverless(app);

const FunctionShield = require('@puresec/function-shield');
FunctionShield.configure({
    policy: {
        // 'block' mode => active blocking
        // 'alert' mode => log only
        // 'allow' mode => allowed, implicitly occurs if key does not exist
        outbound_connectivity: "alert",
        read_write_tmp: "block",
        create_child_process: "block",
        read_handler: "alert"
    },
    token: 'tokenhere'
});

module.exports.server = async (event, context) => {
    return await handler(event, context);
};
```

Which worked. But when I tried writing to /tmp from a route within the app (pretending to be naughty code) it let me do it.

However I _then_ figured what it wanted me to do was include that FunctionShield in the file. So I moved those lines above into a separate file, and then included that in app.js:

`const FunctionShield = require('./shield')`

... and _then_ when I tried writing to /tmp from that app.js file, it did indeed block it. So it's now working. I wondered if that was the correct approach. But it seems like it is.

**Comment by 0xh0b0** [comment]
You should load FunctionShield as early as possible.
For example:
```javascript
const FunctionShield = require('@puresec/function-shield');
FunctionShield.configure({
    policy: {
        // 'block' mode => active blocking
        // 'alert' mode => log only
        // 'allow' mode => allowed, implicitly occurs if key does not exist
        outbound_connectivity: "alert",
        read_write_tmp: "block",
        create_child_process: "block",
        read_handler: "alert"
    },
    token: 'tokenhere'
});
const serverless = require('serverless-http');
const app = require('./app');
const handler = serverless(app);

module.exports.server = async (event, context) => {
    return await handler(event, context);
};
```
Any policy violation that occurs after calling `FunctionShield.configure` should be blocked.
In your case, did you write to '/tmp' in one of the express's handler functions?
Otherwise, it could run before `FunctionShield.configure` call.

**Comment by gregmsanderson** [comment]
Ok, I'll give that a try, changing the order within that main index file.

Yes, I tried writing to /tmp within the app.js file (doing it within index.js was correctly blocked). The order could have been the issue, if so.

**Comment by gregmsanderson** [comment]
Yep, you were right. The FunctionShield just needed to be on the very first line. Great :)
