### ISSUE TITLE
Allow whitelist hosts for outbound connection

### ISSUE THREAD

**Issue by hoangleitvn** [puresec/FunctionShield#8]
Is that possible to configure whitelist hosts that allow outbound connection without update policy? Sometimes we need to send an outbound request to a well-known host (trusted host), so it would explicitly allowed

**Comment by 0xh0b0** [comment]
Thanks for your interest Hoang.
FunctionShield provides a limited set of useful capabilities.
Support for custom policies is part of our commercial offering.
Please refer to our PureSec / Prisma Cloud websites for more information.
